name:                           coverage

on:                             [pull_request]
jobs:
  test:
    name:                       Code coverage
    runs-on:                    ubuntu-latest
    container:
      image:                    xd009642/tarpaulin:develop-nightly
      options:                  --security-opt seccomp=unconfined
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2

      - name:                   Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --workspace --line --timeout 120 --exclude-files "*precis-tools*" --out Xml

      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v3
        with:
          fail_ci_if_error:     true
