name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with networking
      run: cargo build --features networking --verbose
    - name: Build
      run: cargo build --verbose
    - run: rustup component add clippy
    - run: cargo clippy --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose

#  cargo_check:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install cargo-sort
#      run: cargo install --locked cargo-sort
#    - run: cargo sort -w -c

  spellcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-spellcheck

    - uses: actions/checkout@v3

    - name: Run cargo spellcheck
      run: cargo-spellcheck --code 1 --cfg=.github/workflows/spellchecker.cfg

  cargo_careful:

    runs-on: ubuntu-latest

    steps:
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-careful

    - uses: actions/checkout@v3
    - name: Install minimal nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly

    - name: Run cargo careful
      run: cargo +nightly careful test

  cargo_machete:

    runs-on: ubuntu-latest

    steps:
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-machete
    - uses: actions/checkout@v3

    - name: Run cargo machete
      run: cargo machete
